services:
    app:
        build: .
        container_name: relamudia_app
        restart: always
        ports:
            - "8001:80" # Map internal 80 to external 8001
        env_file:
            - .env
        volumes:
            - relamudia_app_items:/app/public/image/items
        depends_on:
            db:
                condition: service_healthy
        networks:
            - relamudia_network

    db:
        image: mysql:8.0
        container_name: relamudia_db
        restart: always
        ports:
            - "3301:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-relamudia}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - relamudia_db_data:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - relamudia_network

networks:
    relamudia_network:
        driver: bridge

volumes:
    relamudia_db_data:
    relamudia_app_items:
